Settings:
  # noinspection SpellCheckingInspection
  Prefix: '&8[#4ec483&lPUUIDs&8]'
  Update-Checking: true
  Cooldowns:
    On-Time:
      Enabled: true
      Seconds: 5
  File-Cleanup:
    Enabled: true
    Clean-Essentials: true
    Max-Days: 365
  Metrics: true
  Debug: false
Messages:
  No-Permission: '&c&lSorry! &fYou are not able to do that.'
Advanced:
  # Only mess with the following if you are sure as to what you're doing.
  Save-Rate-Ticks: 10
  Max-Processes-Per-Queue: 25
  Allow-Post-Startup-Connections: false
  Allow-Unsafe-Reloads: false
  UUID: "0"