name: PUUIDs
main: com.zachduda.puuids.Main
website: https://zachduda.com/puuids
authors: [zach_attack]
version: 4.0.0
folia-supported: true
api-version: 1.13
softdepend: [ Essentials ]
load: STARTUP
permissions:
  puuids.admin:
    description: Admin permission for puuids
    default: op
commands:
  puuids:
    description: The main plugin command for the puuids system.